webtalk_init -webtalk_dir C:/Users/QADEER KHAN/Documents/lab41/lab41.sim/sim_1/behav/xsim/xsim.dir/loopback_testbench_v_tf_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec  3 09:59:52 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "35427b5d-ea2b-4318-8a7d-1101a33c1fa4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "daa1c6d1415945b0b2128e601514497f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "20539640100 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "150.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18232_KB" -context "xsim\\usage"
webtalk_transmit -clientid 234637897 -regid "" -xml C:/Users/QADEER KHAN/Documents/lab41/lab41.sim/sim_1/behav/xsim/xsim.dir/loopback_testbench_v_tf_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/QADEER KHAN/Documents/lab41/lab41.sim/sim_1/behav/xsim/xsim.dir/loopback_testbench_v_tf_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/QADEER KHAN/Documents/lab41/lab41.sim/sim_1/behav/xsim/xsim.dir/loopback_testbench_v_tf_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
